export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PROJECT_REPOSITORY = Symbol('PROJECT_REPOSITORY');
export const PLAN_REPOSITORY = Symbol('PLAN_REPOSITORY');
export const TEAM_REPOSITORY = Symbol('TEAM_REPOSITORY');
export const TEAM_ACTIVITY_REPOSITORY = Symbol('TEAM_ACTIVITY_REPOSITORY');
export const TEAM_MEMBER_REPOSITORY = Symbol('TEAM_MEMBER_REPOSITORY');
export const TEAM_INVITATION_REPOSITORY = Symbol('TEAM_INVITATION_REPOSITORY');
export const GIT_CONNECTION_REPOSITORY = Symbol('GIT_CONNECTION_REPOSITORY');
export const CREDENTIAL_REPOSITORY = Symbol('CREDENTIAL_REPOSITORY');
export const SECURITY_AUDIT_REPOSITORY = Symbol('SECURITY_AUDIT_REPOSITORY');
export const WORKSPACE_REPOSITORY = Symbol('WORKSPACE_REPOSITORY');
export const SETUP_STATE_REPOSITORY = Symbol('SETUP_STATE_REPOSITORY');
export const ROLLBACK_ACTION_REPOSITORY = Symbol('ROLLBACK_ACTION_REPOSITORY');

// ─── Agent Orchestrator Repositories ────────────────────────────────────────
export const EXECUTION_PLAN_REPOSITORY = Symbol('EXECUTION_PLAN_REPOSITORY');
export const AGENT_EXECUTION_REPOSITORY = Symbol('AGENT_EXECUTION_REPOSITORY');
export const AGENT_CONTEXT_REPOSITORY = Symbol('AGENT_CONTEXT_REPOSITORY');
export const WORKER_POOL_CONFIG_REPOSITORY = Symbol(
  'WORKER_POOL_CONFIG_REPOSITORY',
);
export const AGENT_PROFILE_REPOSITORY = Symbol('AGENT_PROFILE_REPOSITORY');
