module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'backend',
        'frontend',
        'wizard',
        'auth',
        'llm',
        'git',
        'execution',
        'plans',
        'projects',
        'teams',
        'security',
        'setup',
        'docs',
        'deps',
        'ci',
        'config',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 100],
  },
};
