import { Injectable, Logger } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { NeonSetupService } from './neon-setup.service';
import { VercelSetupService } from './vercel-setup.service';
import { RailwaySetupService } from './railway-setup.service';
import { SetupState, SetupStateDocument, SetupStatus, TaskStatus } from './schemas/setup-state.schema';
import { RollbackAction, RollbackActionDocument, RollbackStatus } from './schemas/rollback-action.schema';
import { ISetupExecutor } from './executors/ISetupExecutor';
import { NeonExecutor } from './executors/NeonExecutor';
import { VercelExecutor } from './executors/VercelExecutor';
import { RailwayExecutor } from './executors/RailwayExecutor';
import {
  SetupOrchestratorConfig,
  SetupResult,
  SetupTask,
  SetupTaskStatus,
  SetupProvider,
  NeonSetupResult,
  VercelSetupResult,
  RailwaySetupResult,
  VercelEnvironmentVariable,
  SetupState as SetupStateDto,
} from './dto/setup.dto';

@Injectable()
export class SetupOrchestratorService {
  private readonly logger = new Logger(SetupOrchestratorService.name);

  constructor(
    @InjectModel(SetupState.name) private setupStateModel: Model<SetupStateDocument>,
    @InjectModel(RollbackAction.name) private rollbackActionModel: Model<RollbackActionDocument>,
    private readonly neonSetupService: NeonSetupService,
    private readonly vercelSetupService: VercelSetupService,
    private readonly railwaySetupService: RailwaySetupService,
    private readonly neonExecutor: NeonExecutor,
    private readonly vercelExecutor: VercelExecutor,
    private readonly railwayExecutor: RailwayExecutor,
  ) {
    this.executors = [this.neonExecutor, this.vercelExecutor, this.railwayExecutor];
  }

  private readonly executors: ISetupExecutor[];

  private generateSetupId(): string {
    return `setup-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  }

  private initializeTasks(config: SetupOrchestratorConfig): SetupTask[] {
    const tasks: SetupTask[] = [];

    if (config.providers.neon) {
      tasks.push({
        id: `task-neon-${Date.now()}`,
        name: 'Setup Neon Database',
        provider: SetupProvider.NEON,
        status: SetupTaskStatus.PENDING,
        estimatedDuration: 120, // 2 minutes
        steps: [],
      });
    }

    if (config.providers.vercel) {
      tasks.push({
        id: `task-vercel-${Date.now()}`,
        name: 'Setup Vercel Frontend',
        provider: SetupProvider.VERCEL,
        status: SetupTaskStatus.PENDING,
        estimatedDuration: 180, // 3 minutes
        steps: [],
      });
    }

    if (config.providers.railway) {
      tasks.push({
        id: `task-railway-${Date.now()}`,
        name: 'Setup Railway Backend',
        provider: SetupProvider.RAILWAY,
        status: SetupTaskStatus.PENDING,
        estimatedDuration: 180, // 3 minutes
        steps: [],
      });
    }

    return tasks;
  }

  private calculateProgress(tasks: SetupTask[]): number {
    const totalTasks = tasks.length;
    if (totalTasks === 0) return 100;

    const completedTasks = tasks.filter(
      (t) => t.status === SetupTaskStatus.COMPLETED,
    ).length;
    const inProgressTasks = tasks.filter(
      (t) => t.status === SetupTaskStatus.IN_PROGRESS,
    ).length;

    return Math.floor(((completedTasks + inProgressTasks * 0.5) / totalTasks) * 100);
  }

  private generateEnvFile(state: SetupStateDocument): string {
    const lines: string[] = ['# Generated by VibeCoding Setup', ''];

    if (state.credentials?.databaseUrl) {
      lines.push(`# Database`);
      lines.push(`DATABASE_URL="${state.credentials.databaseUrl}"`);
      lines.push('');
    }

    if (state.credentials?.redisUrl) {
      lines.push(`# Redis`);
      lines.push(`REDIS_URL="${state.credentials.redisUrl}"`);
      lines.push('');
    }

    if (state.urls?.frontend) {
      lines.push(`# Frontend`);
      lines.push(`NEXT_PUBLIC_APP_URL="${state.urls.frontend}"`);
      lines.push('');
    }

    if (state.urls?.backend) {
      lines.push(`# Backend`);
      lines.push(`NEXT_PUBLIC_API_URL="${state.urls.backend}"`);
      lines.push('');
    }

    return lines.join('\n');
  }

  private generateNextSteps(state: SetupStateDocument): string[] {
    const steps: string[] = [];

    if (state.urls?.dashboards?.neon) {
      steps.push(`Review your Neon database at: ${state.urls.dashboards.neon}`);
    }

    if (state.urls?.dashboards?.vercel) {
      steps.push(`Review your Vercel deployment at: ${state.urls.dashboards.vercel}`);
    }

    if (state.urls?.dashboards?.railway) {
      steps.push(`Review your Railway services at: ${state.urls.dashboards.railway}`);
    }

    steps.push('Copy the generated .env file to your local project');
    steps.push('Run database migrations if needed');
    steps.push('Test your application endpoints');

    return steps;
  }

  private async addRollbackAction(
    setupId: string,
    provider: SetupProvider,
    action: string,
    resourceId: string,
    taskId: string,
    order: number,
  ): Promise<void> {
    const rollbackAction = new this.rollbackActionModel({
      setupId,
      provider,
      action,
      resourceId,
      taskId,
      order,
      status: RollbackStatus.PENDING,
    });
    await rollbackAction.save();
  }

  async execute(
    config: SetupOrchestratorConfig,
    tokens?: {
      neon?: string;
      vercel?: string;
      railway?: string;
    },
  ): Promise<{ setupId: string; result: SetupResult }> {
    const setupId = this.generateSetupId();
    const tasks = this.initializeTasks(config);
    let rollbackOrder = 0;

    // Create initial state in MongoDB
    const setupState = new this.setupStateModel({
      setupId,
      userId: config.userId,
      projectId: config.projectId,
      projectName: config.projectName,
      status: SetupStatus.IN_PROGRESS,
      tasks,
      urls: { dashboards: {} },
      credentials: {},
      currentTaskIndex: 0,
      progress: 0,
      startedAt: new Date(),
      config,
    });
    await setupState.save();

    this.logger.log(`Starting setup: ${setupId}`);

    try {
      for (let i = 0; i < tasks.length; i++) {
        const task = tasks[i];
        const executor = this.executors.find((e) => e.canExecute(task.provider));

        if (!executor) {
          this.logger.warn(`No executor found for provider ${task.provider}`);
          continue;
        }

        // Update status IN_PROGRESS
        task.status = SetupTaskStatus.IN_PROGRESS;
        task.startedAt = new Date();

        await this.setupStateModel.findOneAndUpdate(
          { setupId },
          {
            currentTaskIndex: i,
            tasks,
            progress: this.calculateProgress(tasks),
          },
        ).exec();

        // Reload state to get updated credentials for the executor
        const currentState = await this.setupStateModel.findOne({ setupId }).exec();
        if (!currentState) throw new Error('Setup state not found');

        try {
          // Determine token
          let token: string | undefined;
          if (task.provider === SetupProvider.NEON) token = tokens?.neon;
          else if (task.provider === SetupProvider.VERCEL) token = tokens?.vercel;
          else if (task.provider === SetupProvider.RAILWAY) token = tokens?.railway;

          const result = await executor.execute(config, currentState, task, token);

          // Update task with result
          task.steps = result.steps;
          task.result = result;
          task.status = SetupTaskStatus.COMPLETED;
          task.completedAt = new Date();

          // Update global state based on result
          const updates: Record<string, any> = {
            tasks,
            progress: this.calculateProgress(tasks),
          };

          if (task.provider === SetupProvider.NEON) {
            const res = result as NeonSetupResult;
            updates['urls.database'] = res.dashboardUrl;
            updates['urls.dashboards.neon'] = res.dashboardUrl;
            updates['credentials.databaseUrl'] = res.connectionStrings.main;
          } else if (task.provider === SetupProvider.VERCEL) {
            const res = result as VercelSetupResult;
            updates['urls.frontend'] = res.url;
            updates['urls.dashboards.vercel'] = res.dashboardUrl;
          } else if (task.provider === SetupProvider.RAILWAY) {
            const res = result as RailwaySetupResult;
            updates['urls.dashboards.railway'] = res.dashboardUrl;
            if (res.services.api) updates['urls.backend'] = res.services.api.url;
            if (res.services.redis) updates['credentials.redisUrl'] = res.services.redis.connectionString;
          }

          await this.setupStateModel.findOneAndUpdate({ setupId }, updates).exec();

          await this.addRollbackAction(
            setupId,
            task.provider,
            'delete-project',
            result.projectId,
            task.id,
            rollbackOrder++,
          );
        } catch (error) {
          task.status = SetupTaskStatus.FAILED;
          task.error = error instanceof Error ? error.message : 'Unknown error';
          await this.setupStateModel.findOneAndUpdate({ setupId }, { tasks }).exec();
          throw error;
        }
      }

      // All tasks completed
      const finalState = await this.setupStateModel.findOneAndUpdate(
        { setupId },
        {
          status: SetupStatus.COMPLETED,
          completedAt: new Date(),
          progress: 100,
          tasks,
        },
        { new: true },
      ).exec();

      if (!finalState) {
        throw new Error('Failed to retrieve final state');
      }

      const generatedEnvFile = this.generateEnvFile(finalState);
      const nextSteps = this.generateNextSteps(finalState);

      await this.setupStateModel.findOneAndUpdate(
        { setupId },
        { generatedEnvFile, nextSteps },
      ).exec();

      const result: SetupResult = {
        success: true,
        state: this.convertToDto(finalState),
        urls: finalState.urls as SetupStateDto['urls'],
        credentials: finalState.credentials,
        nextSteps,
        generatedEnvFile,
      };

      this.logger.log(`Setup completed successfully: ${setupId}`);

      return { setupId, result };
    } catch (error) {
      this.logger.error(`Setup failed: ${setupId}`, error);

      await this.setupStateModel.findOneAndUpdate(
        { setupId },
        {
          status: SetupStatus.FAILED,
          progress: this.calculateProgress(tasks),
          tasks,
          errorMessage: error instanceof Error ? error.message : 'Unknown error',
        },
      ).exec();

      // Auto-rollback on failure
      await this.rollback(setupId, tokens);

      const failedState = await this.setupStateModel.findOne({ setupId }).exec();

      return {
        setupId,
        result: {
          success: false,
          state: failedState ? this.convertToDto(failedState) : {
            status: SetupTaskStatus.FAILED,
            tasks,
            urls: { dashboards: {} },
            credentials: {},
            currentTaskIndex: 0,
            progress: 0,
          },
          urls: failedState?.urls as SetupStateDto['urls'] || { dashboards: {} },
          credentials: failedState?.credentials || {},
          nextSteps: ['Fix the error and try again'],
        },
      };
    }
  }

  async rollback(
    setupId: string,
    tokens?: {
      neon?: string;
      vercel?: string;
      railway?: string;
    },
  ): Promise<void> {
    const rollbackActions = await this.rollbackActionModel
      .find({ setupId, status: RollbackStatus.PENDING })
      .sort({ order: -1 })
      .exec();

    if (rollbackActions.length === 0) {
      this.logger.log(`No resources to rollback for setup: ${setupId}`);
      return;
    }

    this.logger.log(`Starting rollback for setup: ${setupId}`);

    for (const action of rollbackActions) {
      try {
        const executor = this.executors.find((e) => e.canExecute(action.provider as SetupProvider));

        if (executor) {
          let token: string | undefined;
          if (action.provider === SetupProvider.NEON) token = tokens?.neon;
          else if (action.provider === SetupProvider.VERCEL) token = tokens?.vercel;
          else if (action.provider === SetupProvider.RAILWAY) token = tokens?.railway;

          await executor.rollback(action.resourceId, token);
        } else {
          this.logger.warn(`No executor found for rollback of ${action.provider}`);
        }

        await this.rollbackActionModel.findByIdAndUpdate(action._id, {
          status: RollbackStatus.COMPLETED,
          executedAt: new Date(),
        }).exec();

        // Update task status to rolled back
        await this.setupStateModel.findOneAndUpdate(
          { setupId, 'tasks.id': action.taskId },
          { $set: { 'tasks.$.status': TaskStatus.ROLLED_BACK } },
        ).exec();
      } catch (error) {
        this.logger.error(
          `Failed to rollback ${action.provider} resource: ${action.resourceId}`,
          error,
        );

        await this.rollbackActionModel.findByIdAndUpdate(action._id, {
          status: RollbackStatus.FAILED,
          error: error instanceof Error ? error.message : 'Unknown error',
          executedAt: new Date(),
        }).exec();
      }
    }

    await this.setupStateModel.findOneAndUpdate(
      { setupId },
      { status: SetupStatus.ROLLED_BACK },
    ).exec();

    this.logger.log(`Rollback completed for setup: ${setupId}`);
  }

  getStatus(setupId: string): SetupStateDto | null {
    // This is now async but keeping sync interface for backward compatibility
    // Caller should use getStatusAsync instead
    return null;
  }

  async getStatusAsync(setupId: string): Promise<SetupStateDto | null> {
    const state = await this.setupStateModel.findOne({ setupId }).exec();
    if (!state) return null;
    return this.convertToDto(state);
  }

  async validateAllTokens(tokens: {
    neon?: string;
    vercel?: string;
    railway?: string;
  }): Promise<{
    neon?: { valid: boolean; accountInfo?: unknown; error?: string };
    vercel?: { valid: boolean; accountInfo?: unknown; error?: string };
    railway?: { valid: boolean; accountInfo?: unknown; error?: string };
  }> {
    const results: {
      neon?: { valid: boolean; accountInfo?: unknown; error?: string };
      vercel?: { valid: boolean; accountInfo?: unknown; error?: string };
      railway?: { valid: boolean; accountInfo?: unknown; error?: string };
    } = {};

    if (tokens.neon) {
      results.neon = await this.neonSetupService.validateToken(tokens.neon);
    }

    if (tokens.vercel) {
      results.vercel = await this.vercelSetupService.validateToken(tokens.vercel);
    }

    if (tokens.railway) {
      results.railway = await this.railwaySetupService.validateToken(tokens.railway);
    }

    return results;
  }

  private convertToDto(state: SetupStateDocument): SetupStateDto {
    return {
      status: state.status as unknown as SetupTaskStatus,
      tasks: state.tasks.map((t) => ({
        id: t.id,
        name: t.name,
        provider: t.provider as SetupProvider,
        status: t.status as unknown as SetupTaskStatus,
        estimatedDuration: t.estimatedDuration,
        steps: (t.steps || []).map((step, index) =>
          typeof step === 'string'
            ? { id: `step-${index}`, name: step, status: SetupTaskStatus.COMPLETED }
            : step
        ),
        error: t.error,
        startedAt: t.startedAt,
        completedAt: t.completedAt,
        result: t.result as NeonSetupResult | VercelSetupResult | RailwaySetupResult | undefined,
      })),
      urls: state.urls as SetupStateDto['urls'],
      credentials: state.credentials,
      currentTaskIndex: state.currentTaskIndex,
      progress: state.progress,
      startedAt: state.startedAt,
      completedAt: state.completedAt,
    };
  }
}
