import { Injectable, Logger } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { NeonSetupService } from './neon-setup.service';
import { VercelSetupService } from './vercel-setup.service';
import { RailwaySetupService } from './railway-setup.service';
import { SetupState, SetupStateDocument, SetupStatus, TaskStatus } from './schemas/setup-state.schema';
import { RollbackAction, RollbackActionDocument, RollbackStatus } from './schemas/rollback-action.schema';
import {
  SetupOrchestratorConfig,
  SetupResult,
  SetupTask,
  SetupTaskStatus,
  SetupProvider,
  NeonSetupResult,
  VercelSetupResult,
  RailwaySetupResult,
  VercelEnvironmentVariable,
  SetupState as SetupStateDto,
} from './dto/setup.dto';

@Injectable()
export class SetupOrchestratorService {
  private readonly logger = new Logger(SetupOrchestratorService.name);

  constructor(
    @InjectModel(SetupState.name) private setupStateModel: Model<SetupStateDocument>,
    @InjectModel(RollbackAction.name) private rollbackActionModel: Model<RollbackActionDocument>,
    private readonly neonSetupService: NeonSetupService,
    private readonly vercelSetupService: VercelSetupService,
    private readonly railwaySetupService: RailwaySetupService,
  ) {}

  private generateSetupId(): string {
    return `setup-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  }

  private initializeTasks(config: SetupOrchestratorConfig): SetupTask[] {
    const tasks: SetupTask[] = [];

    if (config.providers.neon) {
      tasks.push({
        id: `task-neon-${Date.now()}`,
        name: 'Setup Neon Database',
        provider: SetupProvider.NEON,
        status: SetupTaskStatus.PENDING,
        estimatedDuration: 120, // 2 minutes
        steps: [],
      });
    }

    if (config.providers.vercel) {
      tasks.push({
        id: `task-vercel-${Date.now()}`,
        name: 'Setup Vercel Frontend',
        provider: SetupProvider.VERCEL,
        status: SetupTaskStatus.PENDING,
        estimatedDuration: 180, // 3 minutes
        steps: [],
      });
    }

    if (config.providers.railway) {
      tasks.push({
        id: `task-railway-${Date.now()}`,
        name: 'Setup Railway Backend',
        provider: SetupProvider.RAILWAY,
        status: SetupTaskStatus.PENDING,
        estimatedDuration: 180, // 3 minutes
        steps: [],
      });
    }

    return tasks;
  }

  private calculateProgress(tasks: SetupTask[]): number {
    const totalTasks = tasks.length;
    if (totalTasks === 0) return 100;

    const completedTasks = tasks.filter(
      (t) => t.status === SetupTaskStatus.COMPLETED,
    ).length;
    const inProgressTasks = tasks.filter(
      (t) => t.status === SetupTaskStatus.IN_PROGRESS,
    ).length;

    return Math.floor(((completedTasks + inProgressTasks * 0.5) / totalTasks) * 100);
  }

  private generateEnvFile(state: SetupStateDocument): string {
    const lines: string[] = ['# Generated by VibeCoding Setup', ''];

    if (state.credentials?.databaseUrl) {
      lines.push(`# Database`);
      lines.push(`DATABASE_URL="${state.credentials.databaseUrl}"`);
      lines.push('');
    }

    if (state.credentials?.redisUrl) {
      lines.push(`# Redis`);
      lines.push(`REDIS_URL="${state.credentials.redisUrl}"`);
      lines.push('');
    }

    if (state.urls?.frontend) {
      lines.push(`# Frontend`);
      lines.push(`NEXT_PUBLIC_APP_URL="${state.urls.frontend}"`);
      lines.push('');
    }

    if (state.urls?.backend) {
      lines.push(`# Backend`);
      lines.push(`NEXT_PUBLIC_API_URL="${state.urls.backend}"`);
      lines.push('');
    }

    return lines.join('\n');
  }

  private generateNextSteps(state: SetupStateDocument): string[] {
    const steps: string[] = [];

    if (state.urls?.dashboards?.neon) {
      steps.push(`Review your Neon database at: ${state.urls.dashboards.neon}`);
    }

    if (state.urls?.dashboards?.vercel) {
      steps.push(`Review your Vercel deployment at: ${state.urls.dashboards.vercel}`);
    }

    if (state.urls?.dashboards?.railway) {
      steps.push(`Review your Railway services at: ${state.urls.dashboards.railway}`);
    }

    steps.push('Copy the generated .env file to your local project');
    steps.push('Run database migrations if needed');
    steps.push('Test your application endpoints');

    return steps;
  }

  private async addRollbackAction(
    setupId: string,
    provider: SetupProvider,
    action: string,
    resourceId: string,
    taskId: string,
    order: number,
  ): Promise<void> {
    const rollbackAction = new this.rollbackActionModel({
      setupId,
      provider,
      action,
      resourceId,
      taskId,
      order,
      status: RollbackStatus.PENDING,
    });
    await rollbackAction.save();
  }

  async execute(
    config: SetupOrchestratorConfig,
    tokens?: {
      neon?: string;
      vercel?: string;
      railway?: string;
    },
  ): Promise<{ setupId: string; result: SetupResult }> {
    const setupId = this.generateSetupId();
    const tasks = this.initializeTasks(config);
    let rollbackOrder = 0;

    // Create initial state in MongoDB
    const setupState = new this.setupStateModel({
      setupId,
      userId: config.userId,
      projectId: config.projectId,
      projectName: config.projectName,
      status: SetupStatus.IN_PROGRESS,
      tasks,
      urls: { dashboards: {} },
      credentials: {},
      currentTaskIndex: 0,
      progress: 0,
      startedAt: new Date(),
      config,
    });
    await setupState.save();

    this.logger.log(`Starting setup: ${setupId}`);

    try {
      // Execute Neon setup
      const neonTaskIndex = tasks.findIndex((t) => t.provider === SetupProvider.NEON);
      if (neonTaskIndex !== -1 && config.providers.neon) {
        const neonTask = tasks[neonTaskIndex];
        neonTask.status = SetupTaskStatus.IN_PROGRESS;
        neonTask.startedAt = new Date();

        await this.setupStateModel.findOneAndUpdate(
          { setupId },
          {
            currentTaskIndex: neonTaskIndex,
            tasks,
            progress: this.calculateProgress(tasks),
          },
        ).exec();

        try {
          const neonResult = await this.neonSetupService.execute(
            config.providers.neon,
            tokens?.neon,
          );

          neonTask.steps = neonResult.steps;
          neonTask.result = neonResult as NeonSetupResult;
          neonTask.status = SetupTaskStatus.COMPLETED;
          neonTask.completedAt = new Date();

          await this.setupStateModel.findOneAndUpdate(
            { setupId },
            {
              tasks,
              'urls.database': neonResult.dashboardUrl,
              'urls.dashboards.neon': neonResult.dashboardUrl,
              'credentials.databaseUrl': neonResult.connectionStrings.main,
              progress: this.calculateProgress(tasks),
            },
          ).exec();

          await this.addRollbackAction(
            setupId,
            SetupProvider.NEON,
            'delete-project',
            neonResult.projectId,
            neonTask.id,
            rollbackOrder++,
          );
        } catch (error) {
          neonTask.status = SetupTaskStatus.FAILED;
          neonTask.error = error instanceof Error ? error.message : 'Unknown error';
          await this.setupStateModel.findOneAndUpdate({ setupId }, { tasks }).exec();
          throw error;
        }
      }

      // Reload state to get updated credentials
      let currentState = await this.setupStateModel.findOne({ setupId }).exec();

      // Execute Vercel setup
      const vercelTaskIndex = tasks.findIndex((t) => t.provider === SetupProvider.VERCEL);
      if (vercelTaskIndex !== -1 && config.providers.vercel) {
        const vercelTask = tasks[vercelTaskIndex];
        vercelTask.status = SetupTaskStatus.IN_PROGRESS;
        vercelTask.startedAt = new Date();

        await this.setupStateModel.findOneAndUpdate(
          { setupId },
          {
            currentTaskIndex: vercelTaskIndex,
            tasks,
            progress: this.calculateProgress(tasks),
          },
        ).exec();

        // Prepare env vars for Vercel
        const envVars: VercelEnvironmentVariable[] = [];
        if (currentState?.credentials?.databaseUrl) {
          envVars.push({
            key: 'DATABASE_URL',
            value: currentState.credentials.databaseUrl,
            target: ['production', 'preview'],
          });
        }
        if (config.envVars) {
          for (const [key, value] of Object.entries(config.envVars)) {
            envVars.push({
              key,
              value,
              target: ['production', 'preview', 'development'],
            });
          }
        }

        try {
          const vercelResult = await this.vercelSetupService.execute(
            config.providers.vercel,
            envVars,
            undefined, // gitSource
            tokens?.vercel,
          );

          vercelTask.steps = vercelResult.steps;
          vercelTask.result = vercelResult as VercelSetupResult;
          vercelTask.status = SetupTaskStatus.COMPLETED;
          vercelTask.completedAt = new Date();

          await this.setupStateModel.findOneAndUpdate(
            { setupId },
            {
              tasks,
              'urls.frontend': vercelResult.url,
              'urls.dashboards.vercel': vercelResult.dashboardUrl,
              progress: this.calculateProgress(tasks),
            },
          ).exec();

          await this.addRollbackAction(
            setupId,
            SetupProvider.VERCEL,
            'delete-project',
            vercelResult.projectId,
            vercelTask.id,
            rollbackOrder++,
          );
        } catch (error) {
          vercelTask.status = SetupTaskStatus.FAILED;
          vercelTask.error = error instanceof Error ? error.message : 'Unknown error';
          await this.setupStateModel.findOneAndUpdate({ setupId }, { tasks }).exec();
          throw error;
        }
      }

      // Reload state again
      currentState = await this.setupStateModel.findOne({ setupId }).exec();

      // Execute Railway setup
      const railwayTaskIndex = tasks.findIndex((t) => t.provider === SetupProvider.RAILWAY);
      if (railwayTaskIndex !== -1 && config.providers.railway) {
        const railwayTask = tasks[railwayTaskIndex];
        railwayTask.status = SetupTaskStatus.IN_PROGRESS;
        railwayTask.startedAt = new Date();

        await this.setupStateModel.findOneAndUpdate(
          { setupId },
          {
            currentTaskIndex: railwayTaskIndex,
            tasks,
            progress: this.calculateProgress(tasks),
          },
        ).exec();

        // Prepare env vars for Railway
        const envVars: Record<string, string> = {};
        if (currentState?.credentials?.databaseUrl) {
          envVars['DATABASE_URL'] = currentState.credentials.databaseUrl;
        }
        if (currentState?.urls?.frontend) {
          envVars['FRONTEND_URL'] = currentState.urls.frontend;
        }
        if (config.envVars) {
          Object.assign(envVars, config.envVars);
        }

        try {
          const railwayResult = await this.railwaySetupService.execute(
            config.providers.railway,
            undefined, // serviceConfig
            false, // needsRedis
            envVars,
            tokens?.railway,
          );

          railwayTask.steps = railwayResult.steps;
          railwayTask.result = railwayResult as RailwaySetupResult;
          railwayTask.status = SetupTaskStatus.COMPLETED;
          railwayTask.completedAt = new Date();

          const updates: Record<string, any> = {
            tasks,
            'urls.dashboards.railway': railwayResult.dashboardUrl,
            progress: this.calculateProgress(tasks),
          };

          if (railwayResult.services.api) {
            updates['urls.backend'] = railwayResult.services.api.url;
          }
          if (railwayResult.services.redis) {
            updates['credentials.redisUrl'] = railwayResult.services.redis.connectionString;
          }

          await this.setupStateModel.findOneAndUpdate({ setupId }, updates).exec();

          await this.addRollbackAction(
            setupId,
            SetupProvider.RAILWAY,
            'delete-project',
            railwayResult.projectId,
            railwayTask.id,
            rollbackOrder++,
          );
        } catch (error) {
          railwayTask.status = SetupTaskStatus.FAILED;
          railwayTask.error = error instanceof Error ? error.message : 'Unknown error';
          await this.setupStateModel.findOneAndUpdate({ setupId }, { tasks }).exec();
          throw error;
        }
      }

      // All tasks completed
      const finalState = await this.setupStateModel.findOneAndUpdate(
        { setupId },
        {
          status: SetupStatus.COMPLETED,
          completedAt: new Date(),
          progress: 100,
          tasks,
        },
        { new: true },
      ).exec();

      if (!finalState) {
        throw new Error('Failed to retrieve final state');
      }

      const generatedEnvFile = this.generateEnvFile(finalState);
      const nextSteps = this.generateNextSteps(finalState);

      await this.setupStateModel.findOneAndUpdate(
        { setupId },
        { generatedEnvFile, nextSteps },
      ).exec();

      const result: SetupResult = {
        success: true,
        state: this.convertToDto(finalState),
        urls: finalState.urls as SetupStateDto['urls'],
        credentials: finalState.credentials,
        nextSteps,
        generatedEnvFile,
      };

      this.logger.log(`Setup completed successfully: ${setupId}`);

      return { setupId, result };
    } catch (error) {
      this.logger.error(`Setup failed: ${setupId}`, error);

      await this.setupStateModel.findOneAndUpdate(
        { setupId },
        {
          status: SetupStatus.FAILED,
          progress: this.calculateProgress(tasks),
          tasks,
          errorMessage: error instanceof Error ? error.message : 'Unknown error',
        },
      ).exec();

      // Auto-rollback on failure
      await this.rollback(setupId, tokens);

      const failedState = await this.setupStateModel.findOne({ setupId }).exec();

      return {
        setupId,
        result: {
          success: false,
          state: failedState ? this.convertToDto(failedState) : {
            status: SetupTaskStatus.FAILED,
            tasks,
            urls: { dashboards: {} },
            credentials: {},
            currentTaskIndex: 0,
            progress: 0,
          },
          urls: failedState?.urls as SetupStateDto['urls'] || { dashboards: {} },
          credentials: failedState?.credentials || {},
          nextSteps: ['Fix the error and try again'],
        },
      };
    }
  }

  async rollback(
    setupId: string,
    tokens?: {
      neon?: string;
      vercel?: string;
      railway?: string;
    },
  ): Promise<void> {
    const rollbackActions = await this.rollbackActionModel
      .find({ setupId, status: RollbackStatus.PENDING })
      .sort({ order: -1 })
      .exec();

    if (rollbackActions.length === 0) {
      this.logger.log(`No resources to rollback for setup: ${setupId}`);
      return;
    }

    this.logger.log(`Starting rollback for setup: ${setupId}`);

    for (const action of rollbackActions) {
      try {
        switch (action.provider) {
          case SetupProvider.NEON:
            await this.neonSetupService.rollback(action.resourceId, tokens?.neon);
            break;
          case SetupProvider.VERCEL:
            await this.vercelSetupService.rollback(action.resourceId, tokens?.vercel);
            break;
          case SetupProvider.RAILWAY:
            await this.railwaySetupService.rollback(action.resourceId, tokens?.railway);
            break;
        }

        await this.rollbackActionModel.findByIdAndUpdate(action._id, {
          status: RollbackStatus.COMPLETED,
          executedAt: new Date(),
        }).exec();

        // Update task status to rolled back
        await this.setupStateModel.findOneAndUpdate(
          { setupId, 'tasks.id': action.taskId },
          { $set: { 'tasks.$.status': TaskStatus.ROLLED_BACK } },
        ).exec();
      } catch (error) {
        this.logger.error(
          `Failed to rollback ${action.provider} resource: ${action.resourceId}`,
          error,
        );

        await this.rollbackActionModel.findByIdAndUpdate(action._id, {
          status: RollbackStatus.FAILED,
          error: error instanceof Error ? error.message : 'Unknown error',
          executedAt: new Date(),
        }).exec();
      }
    }

    await this.setupStateModel.findOneAndUpdate(
      { setupId },
      { status: SetupStatus.ROLLED_BACK },
    ).exec();

    this.logger.log(`Rollback completed for setup: ${setupId}`);
  }

  getStatus(setupId: string): SetupStateDto | null {
    // This is now async but keeping sync interface for backward compatibility
    // Caller should use getStatusAsync instead
    return null;
  }

  async getStatusAsync(setupId: string): Promise<SetupStateDto | null> {
    const state = await this.setupStateModel.findOne({ setupId }).exec();
    if (!state) return null;
    return this.convertToDto(state);
  }

  async validateAllTokens(tokens: {
    neon?: string;
    vercel?: string;
    railway?: string;
  }): Promise<{
    neon?: { valid: boolean; accountInfo?: unknown; error?: string };
    vercel?: { valid: boolean; accountInfo?: unknown; error?: string };
    railway?: { valid: boolean; accountInfo?: unknown; error?: string };
  }> {
    const results: {
      neon?: { valid: boolean; accountInfo?: unknown; error?: string };
      vercel?: { valid: boolean; accountInfo?: unknown; error?: string };
      railway?: { valid: boolean; accountInfo?: unknown; error?: string };
    } = {};

    if (tokens.neon) {
      results.neon = await this.neonSetupService.validateToken(tokens.neon);
    }

    if (tokens.vercel) {
      results.vercel = await this.vercelSetupService.validateToken(tokens.vercel);
    }

    if (tokens.railway) {
      results.railway = await this.railwaySetupService.validateToken(tokens.railway);
    }

    return results;
  }

  private convertToDto(state: SetupStateDocument): SetupStateDto {
    return {
      status: state.status as unknown as SetupTaskStatus,
      tasks: state.tasks.map((t) => ({
        id: t.id,
        name: t.name,
        provider: t.provider as SetupProvider,
        status: t.status as unknown as SetupTaskStatus,
        estimatedDuration: t.estimatedDuration,
        steps: (t.steps || []).map((step, index) =>
          typeof step === 'string'
            ? { id: `step-${index}`, name: step, status: SetupTaskStatus.COMPLETED }
            : step
        ),
        error: t.error,
        startedAt: t.startedAt,
        completedAt: t.completedAt,
        result: t.result as NeonSetupResult | VercelSetupResult | RailwaySetupResult | undefined,
      })),
      urls: state.urls as SetupStateDto['urls'],
      credentials: state.credentials,
      currentTaskIndex: state.currentTaskIndex,
      progress: state.progress,
      startedAt: state.startedAt,
      completedAt: state.completedAt,
    };
  }
}
