import { Injectable, Logger } from '@nestjs/common';
import { NeonSetupService } from './neon-setup.service';
import { VercelSetupService } from './vercel-setup.service';
import { RailwaySetupService } from './railway-setup.service';
import {
  SetupOrchestratorConfig,
  SetupState,
  SetupResult,
  SetupTask,
  SetupTaskStatus,
  SetupProvider,
  RollbackAction,
  NeonSetupResult,
  VercelSetupResult,
  RailwaySetupResult,
  VercelEnvironmentVariable,
} from './dto/setup.dto';

@Injectable()
export class SetupOrchestratorService {
  private readonly logger = new Logger(SetupOrchestratorService.name);
  private setupStates: Map<string, SetupState> = new Map();
  private rollbackStacks: Map<string, RollbackAction[]> = new Map();

  constructor(
    private readonly neonSetupService: NeonSetupService,
    private readonly vercelSetupService: VercelSetupService,
    private readonly railwaySetupService: RailwaySetupService,
  ) {}

  private generateSetupId(): string {
    return `setup-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  }

  private initializeState(config: SetupOrchestratorConfig): SetupState {
    const tasks: SetupTask[] = [];

    if (config.providers.neon) {
      tasks.push({
        id: `task-neon-${Date.now()}`,
        name: 'Setup Neon Database',
        provider: SetupProvider.NEON,
        status: SetupTaskStatus.PENDING,
        estimatedDuration: 120, // 2 minutes
        steps: [],
      });
    }

    if (config.providers.vercel) {
      tasks.push({
        id: `task-vercel-${Date.now()}`,
        name: 'Setup Vercel Frontend',
        provider: SetupProvider.VERCEL,
        status: SetupTaskStatus.PENDING,
        estimatedDuration: 180, // 3 minutes
        steps: [],
      });
    }

    if (config.providers.railway) {
      tasks.push({
        id: `task-railway-${Date.now()}`,
        name: 'Setup Railway Backend',
        provider: SetupProvider.RAILWAY,
        status: SetupTaskStatus.PENDING,
        estimatedDuration: 180, // 3 minutes
        steps: [],
      });
    }

    return {
      status: SetupTaskStatus.PENDING,
      tasks,
      urls: {
        dashboards: {},
      },
      credentials: {},
      currentTaskIndex: 0,
      progress: 0,
    };
  }

  private calculateProgress(state: SetupState): number {
    const totalTasks = state.tasks.length;
    if (totalTasks === 0) return 100;

    const completedTasks = state.tasks.filter(
      (t) => t.status === SetupTaskStatus.COMPLETED,
    ).length;
    const inProgressTasks = state.tasks.filter(
      (t) => t.status === SetupTaskStatus.IN_PROGRESS,
    ).length;

    return Math.floor(((completedTasks + inProgressTasks * 0.5) / totalTasks) * 100);
  }

  private generateEnvFile(state: SetupState): string {
    const lines: string[] = ['# Generated by VibeCoding Setup', ''];

    if (state.credentials.databaseUrl) {
      lines.push(`# Database`);
      lines.push(`DATABASE_URL="${state.credentials.databaseUrl}"`);
      lines.push('');
    }

    if (state.credentials.redisUrl) {
      lines.push(`# Redis`);
      lines.push(`REDIS_URL="${state.credentials.redisUrl}"`);
      lines.push('');
    }

    if (state.urls.frontend) {
      lines.push(`# Frontend`);
      lines.push(`NEXT_PUBLIC_APP_URL="${state.urls.frontend}"`);
      lines.push('');
    }

    if (state.urls.backend) {
      lines.push(`# Backend`);
      lines.push(`NEXT_PUBLIC_API_URL="${state.urls.backend}"`);
      lines.push('');
    }

    return lines.join('\n');
  }

  private generateNextSteps(state: SetupState): string[] {
    const steps: string[] = [];

    if (state.urls.dashboards.neon) {
      steps.push(`Review your Neon database at: ${state.urls.dashboards.neon}`);
    }

    if (state.urls.dashboards.vercel) {
      steps.push(`Review your Vercel deployment at: ${state.urls.dashboards.vercel}`);
    }

    if (state.urls.dashboards.railway) {
      steps.push(`Review your Railway services at: ${state.urls.dashboards.railway}`);
    }

    steps.push('Copy the generated .env file to your local project');
    steps.push('Run database migrations if needed');
    steps.push('Test your application endpoints');

    return steps;
  }

  async execute(
    config: SetupOrchestratorConfig,
    tokens?: {
      neon?: string;
      vercel?: string;
      railway?: string;
    },
  ): Promise<{ setupId: string; result: SetupResult }> {
    const setupId = this.generateSetupId();
    const state = this.initializeState(config);
    const rollbackStack: RollbackAction[] = [];

    this.setupStates.set(setupId, state);
    this.rollbackStacks.set(setupId, rollbackStack);

    state.status = SetupTaskStatus.IN_PROGRESS;
    state.startedAt = new Date();

    this.logger.log(`Starting setup: ${setupId}`);

    try {
      // Execute Neon setup
      const neonTask = state.tasks.find((t) => t.provider === SetupProvider.NEON);
      if (neonTask && config.providers.neon) {
        neonTask.status = SetupTaskStatus.IN_PROGRESS;
        neonTask.startedAt = new Date();
        state.currentTaskIndex = state.tasks.indexOf(neonTask);
        state.progress = this.calculateProgress(state);

        try {
          const neonResult = await this.neonSetupService.execute(
            config.providers.neon,
            tokens?.neon,
          );

          neonTask.steps = neonResult.steps;
          neonTask.result = neonResult as NeonSetupResult;
          neonTask.status = SetupTaskStatus.COMPLETED;
          neonTask.completedAt = new Date();

          state.urls.database = neonResult.dashboardUrl;
          state.urls.dashboards.neon = neonResult.dashboardUrl;
          state.credentials.databaseUrl = neonResult.connectionStrings.main;

          rollbackStack.push({
            taskId: neonTask.id,
            provider: SetupProvider.NEON,
            action: 'delete-project',
            resourceId: neonResult.projectId,
          });
        } catch (error) {
          neonTask.status = SetupTaskStatus.FAILED;
          neonTask.error = error instanceof Error ? error.message : 'Unknown error';
          throw error;
        }
      }

      // Execute Vercel setup
      const vercelTask = state.tasks.find((t) => t.provider === SetupProvider.VERCEL);
      if (vercelTask && config.providers.vercel) {
        vercelTask.status = SetupTaskStatus.IN_PROGRESS;
        vercelTask.startedAt = new Date();
        state.currentTaskIndex = state.tasks.indexOf(vercelTask);
        state.progress = this.calculateProgress(state);

        // Prepare env vars for Vercel
        const envVars: VercelEnvironmentVariable[] = [];
        if (state.credentials.databaseUrl) {
          envVars.push({
            key: 'DATABASE_URL',
            value: state.credentials.databaseUrl,
            target: ['production', 'preview'],
          });
        }
        if (config.envVars) {
          for (const [key, value] of Object.entries(config.envVars)) {
            envVars.push({
              key,
              value,
              target: ['production', 'preview', 'development'],
            });
          }
        }

        try {
          const vercelResult = await this.vercelSetupService.execute(
            config.providers.vercel,
            envVars,
            undefined, // gitSource - would be populated from project config
            tokens?.vercel,
          );

          vercelTask.steps = vercelResult.steps;
          vercelTask.result = vercelResult as VercelSetupResult;
          vercelTask.status = SetupTaskStatus.COMPLETED;
          vercelTask.completedAt = new Date();

          state.urls.frontend = vercelResult.url;
          state.urls.dashboards.vercel = vercelResult.dashboardUrl;

          rollbackStack.push({
            taskId: vercelTask.id,
            provider: SetupProvider.VERCEL,
            action: 'delete-project',
            resourceId: vercelResult.projectId,
          });
        } catch (error) {
          vercelTask.status = SetupTaskStatus.FAILED;
          vercelTask.error = error instanceof Error ? error.message : 'Unknown error';
          throw error;
        }
      }

      // Execute Railway setup
      const railwayTask = state.tasks.find((t) => t.provider === SetupProvider.RAILWAY);
      if (railwayTask && config.providers.railway) {
        railwayTask.status = SetupTaskStatus.IN_PROGRESS;
        railwayTask.startedAt = new Date();
        state.currentTaskIndex = state.tasks.indexOf(railwayTask);
        state.progress = this.calculateProgress(state);

        // Prepare env vars for Railway
        const envVars: Record<string, string> = {};
        if (state.credentials.databaseUrl) {
          envVars['DATABASE_URL'] = state.credentials.databaseUrl;
        }
        if (state.urls.frontend) {
          envVars['FRONTEND_URL'] = state.urls.frontend;
        }
        if (config.envVars) {
          Object.assign(envVars, config.envVars);
        }

        try {
          const railwayResult = await this.railwaySetupService.execute(
            config.providers.railway,
            undefined, // serviceConfig
            false, // needsRedis
            envVars,
            tokens?.railway,
          );

          railwayTask.steps = railwayResult.steps;
          railwayTask.result = railwayResult as RailwaySetupResult;
          railwayTask.status = SetupTaskStatus.COMPLETED;
          railwayTask.completedAt = new Date();

          if (railwayResult.services.api) {
            state.urls.backend = railwayResult.services.api.url;
          }
          if (railwayResult.services.redis) {
            state.credentials.redisUrl = railwayResult.services.redis.connectionString;
          }
          state.urls.dashboards.railway = railwayResult.dashboardUrl;

          rollbackStack.push({
            taskId: railwayTask.id,
            provider: SetupProvider.RAILWAY,
            action: 'delete-project',
            resourceId: railwayResult.projectId,
          });
        } catch (error) {
          railwayTask.status = SetupTaskStatus.FAILED;
          railwayTask.error = error instanceof Error ? error.message : 'Unknown error';
          throw error;
        }
      }

      // All tasks completed
      state.status = SetupTaskStatus.COMPLETED;
      state.completedAt = new Date();
      state.progress = 100;

      const result: SetupResult = {
        success: true,
        state,
        urls: state.urls,
        credentials: state.credentials,
        nextSteps: this.generateNextSteps(state),
        generatedEnvFile: this.generateEnvFile(state),
      };

      this.logger.log(`Setup completed successfully: ${setupId}`);

      return { setupId, result };
    } catch (error) {
      this.logger.error(`Setup failed: ${setupId}`, error);

      state.status = SetupTaskStatus.FAILED;
      state.progress = this.calculateProgress(state);

      // Auto-rollback on failure
      await this.rollback(setupId, tokens);

      return {
        setupId,
        result: {
          success: false,
          state,
          urls: state.urls,
          credentials: state.credentials,
          nextSteps: ['Fix the error and try again'],
        },
      };
    }
  }

  async rollback(
    setupId: string,
    tokens?: {
      neon?: string;
      vercel?: string;
      railway?: string;
    },
  ): Promise<void> {
    const rollbackStack = this.rollbackStacks.get(setupId);
    const state = this.setupStates.get(setupId);

    if (!rollbackStack || rollbackStack.length === 0) {
      this.logger.log(`No resources to rollback for setup: ${setupId}`);
      return;
    }

    this.logger.log(`Starting rollback for setup: ${setupId}`);

    // Rollback in reverse order
    for (let i = rollbackStack.length - 1; i >= 0; i--) {
      const action = rollbackStack[i];

      try {
        switch (action.provider) {
          case SetupProvider.NEON:
            await this.neonSetupService.rollback(action.resourceId, tokens?.neon);
            break;
          case SetupProvider.VERCEL:
            await this.vercelSetupService.rollback(action.resourceId, tokens?.vercel);
            break;
          case SetupProvider.RAILWAY:
            await this.railwaySetupService.rollback(action.resourceId, tokens?.railway);
            break;
        }

        action.executedAt = new Date();

        // Update task status
        if (state) {
          const task = state.tasks.find((t) => t.id === action.taskId);
          if (task) {
            task.status = SetupTaskStatus.ROLLED_BACK;
          }
        }
      } catch (error) {
        this.logger.error(
          `Failed to rollback ${action.provider} resource: ${action.resourceId}`,
          error,
        );
      }
    }

    this.logger.log(`Rollback completed for setup: ${setupId}`);
  }

  getStatus(setupId: string): SetupState | null {
    return this.setupStates.get(setupId) || null;
  }

  async validateAllTokens(tokens: {
    neon?: string;
    vercel?: string;
    railway?: string;
  }): Promise<{
    neon?: { valid: boolean; accountInfo?: unknown; error?: string };
    vercel?: { valid: boolean; accountInfo?: unknown; error?: string };
    railway?: { valid: boolean; accountInfo?: unknown; error?: string };
  }> {
    const results: {
      neon?: { valid: boolean; accountInfo?: unknown; error?: string };
      vercel?: { valid: boolean; accountInfo?: unknown; error?: string };
      railway?: { valid: boolean; accountInfo?: unknown; error?: string };
    } = {};

    if (tokens.neon) {
      results.neon = await this.neonSetupService.validateToken(tokens.neon);
    }

    if (tokens.vercel) {
      results.vercel = await this.vercelSetupService.validateToken(tokens.vercel);
    }

    if (tokens.railway) {
      results.railway = await this.railwaySetupService.validateToken(tokens.railway);
    }

    return results;
  }
}
