import { Injectable } from '@nestjs/common';
import {
  GenerateADRDto,
  ADRDocument,
  ADRStatus,
} from './dto/documentation.dto';

@Injectable()
export class AdrGeneratorService {
  private adrCounter = 0;

  generateADR(dto: GenerateADRDto): ADRDocument {
    this.adrCounter++;
    const adrNumber = this.adrCounter.toString().padStart(3, '0');
    const status = dto.status || ADRStatus.ACCEPTED;
    const createdAt = new Date();

    const content = this.generateADRContent(dto, adrNumber, status, createdAt);
    const filePath = `docs/architecture/adr/ADR-${adrNumber}-${this.slugify(dto.title)}.md`;

    return {
      id: `adr-${adrNumber}`,
      title: dto.title,
      status,
      context: dto.context,
      decision: dto.decision,
      consequences: dto.consequences,
      alternatives: dto.alternatives,
      content,
      filePath,
      createdAt,
    };
  }

  private generateADRContent(
    dto: GenerateADRDto,
    adrNumber: string,
    status: ADRStatus,
    createdAt: Date,
  ): string {
    const lines: string[] = [];

    // Header
    lines.push(`# ADR ${adrNumber}: ${dto.title}`);
    lines.push('');

    // Metadata
    lines.push(`**Date:** ${createdAt.toISOString().split('T')[0]}`);
    lines.push(`**Status:** ${this.formatStatus(status)}`);
    lines.push('');

    // Context
    lines.push('## Context');
    lines.push('');
    lines.push(dto.context);
    lines.push('');

    // Decision
    lines.push('## Decision');
    lines.push('');
    lines.push(dto.decision);
    lines.push('');

    // Consequences
    lines.push('## Consequences');
    lines.push('');
    lines.push('### Positive');
    lines.push('');
    for (const positive of dto.consequences.positive) {
      lines.push(`- ${positive}`);
    }
    lines.push('');

    lines.push('### Negative');
    lines.push('');
    for (const negative of dto.consequences.negative) {
      lines.push(`- ${negative}`);
    }
    lines.push('');

    // Alternatives
    if (dto.alternatives && dto.alternatives.length > 0) {
      lines.push('## Alternatives Considered');
      lines.push('');

      for (const alt of dto.alternatives) {
        lines.push(`### ${alt.name}`);
        lines.push('');
        lines.push(alt.description);
        lines.push('');
        lines.push(`**Rejected because:** ${alt.rejected_reason}`);
        lines.push('');
      }
    }

    // Footer
    lines.push('---');
    lines.push('');
    lines.push('*Generated by Vibe Coding Platform*');

    return lines.join('\n');
  }

  private formatStatus(status: ADRStatus): string {
    switch (status) {
      case ADRStatus.PROPOSED:
        return '🟡 Proposed';
      case ADRStatus.ACCEPTED:
        return '✅ Accepted';
      case ADRStatus.DEPRECATED:
        return '⚠️ Deprecated';
      case ADRStatus.SUPERSEDED:
        return '🔄 Superseded';
      default:
        return status;
    }
  }

  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
  }

  generateADRIndex(adrs: ADRDocument[]): string {
    const lines: string[] = [];

    lines.push('# Architecture Decision Records');
    lines.push('');
    lines.push('This directory contains all Architecture Decision Records (ADRs) for this project.');
    lines.push('');
    lines.push('## What is an ADR?');
    lines.push('');
    lines.push('An Architecture Decision Record captures an important architectural decision made along with its context and consequences.');
    lines.push('');
    lines.push('## ADR List');
    lines.push('');
    lines.push('| ID | Title | Status | Date |');
    lines.push('|----|-------|--------|------|');

    for (const adr of adrs) {
      const statusEmoji = this.getStatusEmoji(adr.status);
      const date = adr.createdAt.toISOString().split('T')[0];
      const link = `[${adr.id.toUpperCase()}](${adr.filePath.split('/').pop()})`;
      lines.push(`| ${link} | ${adr.title} | ${statusEmoji} ${adr.status} | ${date} |`);
    }

    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('*Generated by Vibe Coding Platform*');

    return lines.join('\n');
  }

  private getStatusEmoji(status: ADRStatus): string {
    switch (status) {
      case ADRStatus.PROPOSED:
        return '🟡';
      case ADRStatus.ACCEPTED:
        return '✅';
      case ADRStatus.DEPRECATED:
        return '⚠️';
      case ADRStatus.SUPERSEDED:
        return '🔄';
      default:
        return '';
    }
  }

  // Generate common ADR templates
  generateDatabaseADR(
    dbProvider: string,
    reasoning: string[],
    alternatives: { name: string; rejected_reason: string }[],
  ): ADRDocument {
    return this.generateADR({
      projectId: '',
      title: `Use ${dbProvider} as Primary Database`,
      context: `The project requires a database solution that meets our scalability,
cost, and developer experience requirements. After evaluating multiple options,
we need to make a decision on the primary database provider.`,
      decision: `We will use ${dbProvider} as our primary database.\n\n${reasoning.map((r) => `- ${r}`).join('\n')}`,
      consequences: {
        positive: [
          `${dbProvider} provides excellent developer experience`,
          'Competitive pricing for our expected scale',
          'Good integration with our chosen hosting providers',
          'Reliable performance and uptime guarantees',
        ],
        negative: [
          'Vendor lock-in to specific provider',
          'May need to migrate if requirements change significantly',
        ],
      },
      alternatives: alternatives.map((alt) => ({
        name: alt.name,
        description: `${alt.name} was considered as an alternative database provider.`,
        rejected_reason: alt.rejected_reason,
      })),
      status: ADRStatus.ACCEPTED,
    });
  }

  generateArchitectureADR(
    pattern: string,
    description: string,
    pros: string[],
    cons: string[],
  ): ADRDocument {
    return this.generateADR({
      projectId: '',
      title: `Adopt ${pattern} Architecture Pattern`,
      context: `We need to establish the core architectural pattern for this project
to ensure maintainability, scalability, and team productivity.`,
      decision: `We will adopt the ${pattern} architecture pattern.\n\n${description}`,
      consequences: {
        positive: pros,
        negative: cons,
      },
      status: ADRStatus.ACCEPTED,
    });
  }
}
