/**
 * End-to-End Integration Test — Execution Loop
 *
 * Proves the complete flow works:
 *   executeIntent → createPlan → approvePlan → dispatch → queue.add
 *   → AgentJobRunner.process → agent.execute → handleAgentComplete
 *   → onNodeComplete → next nodes → pipeline completed
 *
 * Uses real services with in-memory adapters and mock LLM/repositories.
 */
import { InMemoryQueueAdapter } from '../../providers/adapters/in-memory-queue.adapter';
import { InMemoryCacheAdapter } from '../../providers/adapters/in-memory-cache.adapter';
import { AgentRegistry } from '../../agents/registry/agent-registry';
import { ContextCompiler } from '../../agents/context/context-compiler';
import { OrchestratorService } from '../orchestrator.service';
import { Planner } from '../planner';
import { Scheduler } from '../scheduler';
import { ResultEvaluator } from '../result-evaluator';
import { WorkerPoolManager } from '../worker-pool-manager';
import { AgentJobRunner } from '../agent-job-runner';
import { TraceContext } from '../../observability/trace';
import { loadVibeConfig } from '../../config/vibe-config';
import {
  IAgent,
  AgentInput,
  AgentOutput,
  AgentProfile,
  TaskDefinition,
  CostEstimate,
  ValidationError,
  DAGNode,
} from '../../agents/protocol';

// ─── Mock Agent Factory ───────────────────────────────────────────────────────

function createMockAgent(
  id: string,
  role: string,
  taskTypes: string[],
): IAgent {
  return {
    profile: {
      id,
      name: `${id.charAt(0).toUpperCase() + id.slice(1)}Agent`,
      role,
      capabilities: taskTypes,
      defaultModel: 'fast' as any,
      systemPromptTemplate: '',
    } as AgentProfile,

    async execute(input: AgentInput): Promise<AgentOutput> {
      return {
        taskId: input.taskDefinition.id,
        agentId: id,
        status: 'success',
        artifacts: [
          {
            type: 'code',
            path: `${id}-output.ts`,
            content: `// Generated by ${id} for ${input.taskDefinition.description}`,
          },
        ],
        contextUpdates: [],
        metrics: {
          startedAt: new Date(),
          durationMs: 50,
          tokensUsed: 100,
          costUSD: 0.001,
          llmCalls: 1,
          retries: 0,
        },
        traceId: input.traceId,
      };
    },

    validateInput(_input: AgentInput): ValidationError[] | null {
      return null;
    },

    estimateCost(_input: AgentInput): CostEstimate {
      return {
        estimatedTokens: 100,
        estimatedCostUSD: 0.001,
        tier: 'fast' as any,
      };
    },

    canHandle(task: TaskDefinition): boolean {
      return taskTypes.includes(task.type);
    },
  };
}

// ─── Mock Repositories ────────────────────────────────────────────────────────

function createMockPlanRepo() {
  const plans = new Map<string, any>();
  let counter = 0;

  return {
    create: jest.fn(async (data: any) => {
      const id = `plan-${++counter}`;
      const plan = { ...data, _id: id, id };
      plans.set(id, plan);
      return plan;
    }),
    findById: jest.fn(async (id: string) => {
      const plan = plans.get(id);
      return plan ? { ...plan } : null;
    }),
    update: jest.fn(async (id: string, data: any) => {
      const plan = plans.get(id);
      if (!plan) return null;
      Object.assign(plan, data);
      plans.set(id, plan);
      return plan;
    }),
    find: jest.fn(async () => []),
    findOne: jest.fn(async () => null),
    delete: jest.fn(async () => true),
    count: jest.fn(async () => plans.size),
    findOneAndUpdate: jest.fn(async () => null),
    findOneAndDelete: jest.fn(async () => null),
    updateMany: jest.fn(async () => ({ modifiedCount: 0 })),
    deleteMany: jest.fn(async () => ({ deletedCount: 0 })),
    insertMany: jest.fn(async () => []),
    findMany: jest.fn(async () => []),
    createMany: jest.fn(async () => []),
    exists: jest.fn(async () => false),
    // IExecutionPlanRepository methods
    findByProjectAndStatus: jest.fn(async () => []),
    updateNodeStatus: jest.fn(async () => null),
    getReadyNodes: jest.fn(async (planId: string) => {
      const plan = plans.get(planId);
      if (!plan) return [];
      return plan.dag
        .filter(
          (n: any) =>
            n.status === 'pending' &&
            n.dependencies.every((dep: string) => {
              const depNode = plan.dag.find((d: any) => d.nodeId === dep);
              return depNode && depNode.status === 'completed';
            }),
        )
        .map((n: any) => ({ nodeId: n.nodeId, agentId: n.agentId }));
    }),
    _plans: plans,
  };
}

function createMockExecutionRepo() {
  const executions: any[] = [];

  return {
    create: jest.fn(async (data: any) => {
      const id = `exec-${executions.length + 1}`;
      const exec = { ...data, _id: id, id };
      executions.push(exec);
      return exec;
    }),
    update: jest.fn(async (id: string, data: any) => {
      const exec = executions.find((e) => e._id === id);
      if (exec) Object.assign(exec, data);
      return exec;
    }),
    find: jest.fn(async (filter: any) => {
      return executions.filter((e) => {
        if (filter.pipelineId && e.pipelineId !== filter.pipelineId)
          return false;
        if (filter.status && e.status !== filter.status) return false;
        return true;
      });
    }),
    findById: jest.fn(async () => null),
    findOne: jest.fn(async () => null),
    delete: jest.fn(async () => true),
    count: jest.fn(async () => executions.length),
    findOneAndUpdate: jest.fn(async () => null),
    findOneAndDelete: jest.fn(async () => null),
    updateMany: jest.fn(async () => ({ modifiedCount: 0 })),
    deleteMany: jest.fn(async () => ({ deletedCount: 0 })),
    insertMany: jest.fn(async () => []),
    findMany: jest.fn(async () => []),
    createMany: jest.fn(async () => []),
    exists: jest.fn(async () => false),
    // IAgentExecutionRepository methods
    getMetricsForPipeline: jest.fn(async () => ({
      totalExecutions: 0,
      completedExecutions: 0,
      failedExecutions: 0,
      totalCostUSD: 0,
      totalTokensUsed: 0,
      averageDurationMs: 0,
    })),
    getCostForProject: jest.fn(async () => 0),
    _executions: executions,
  };
}

function createMockContextRepo() {
  return {
    find: jest.fn(async () => []),
    findById: jest.fn(async () => null),
    findOne: jest.fn(async () => null),
    create: jest.fn(async () => ({})),
    update: jest.fn(async () => null),
    delete: jest.fn(async () => true),
    count: jest.fn(async () => 0),
    findOneAndUpdate: jest.fn(async () => null),
    findOneAndDelete: jest.fn(async () => null),
    updateMany: jest.fn(async () => ({ modifiedCount: 0 })),
    deleteMany: jest.fn(async () => ({ deletedCount: 0 })),
    insertMany: jest.fn(async () => []),
    findMany: jest.fn(async () => []),
    createMany: jest.fn(async () => []),
    exists: jest.fn(async () => false),
  };
}

// ─── Test Suite ───────────────────────────────────────────────────────────────

describe('Execution Loop E2E', () => {
  let orchestratorService: OrchestratorService;
  let agentJobRunner: AgentJobRunner;
  let planRepo: ReturnType<typeof createMockPlanRepo>;
  let executionRepo: ReturnType<typeof createMockExecutionRepo>;
  let eventsGateway: any;
  let queueProvider: InMemoryQueueAdapter;
  let agentRegistry: AgentRegistry;

  beforeEach(async () => {
    const vibeConfig = loadVibeConfig();
    queueProvider = new InMemoryQueueAdapter();
    const cache = new InMemoryCacheAdapter();
    planRepo = createMockPlanRepo();
    executionRepo = createMockExecutionRepo();
    const contextRepo = createMockContextRepo();

    // Agent registry with mock agents
    agentRegistry = new AgentRegistry();
    agentRegistry.register(createMockAgent('analyst', 'analyst', ['analysis']));
    agentRegistry.register(
      createMockAgent('architect', 'architect', ['architecture']),
    );
    agentRegistry.register(
      createMockAgent('coder', 'coder', ['code-generation']),
    );
    agentRegistry.register(createMockAgent('tester', 'tester', ['testing']));

    // Context compiler (uses mock repos)
    const contextCompiler = new ContextCompiler(
      contextRepo as any,
      cache,
      vibeConfig,
    );

    // Mock events gateway
    eventsGateway = {
      emitExecutionEvent: jest.fn(),
      emitWorkerStatusUpdate: jest.fn(),
    };

    // Mock VCS provider
    const mockVcs = {
      createBranch: jest.fn().mockResolvedValue(undefined),
      checkout: jest.fn().mockResolvedValue(undefined),
      commit: jest.fn().mockResolvedValue(undefined),
      push: jest.fn().mockResolvedValue(undefined),
      getStatus: jest.fn().mockResolvedValue({ modified: [], untracked: [] }),
      getCurrentBranch: jest.fn().mockResolvedValue('main'),
      getDiff: jest.fn().mockResolvedValue(''),
      getLog: jest.fn().mockResolvedValue([]),
      mergeBranch: jest.fn().mockResolvedValue(undefined),
    };

    // Mock Planner that creates a deterministic 3-node DAG
    const mockPlanner = {
      createPlan: jest.fn(async (intent: string, projectId: string) => {
        const dag: DAGNode[] = [
          {
            nodeId: 'n1',
            agentId: 'analyst',
            taskDefinition: {
              id: 't1',
              type: 'analysis' as any,
              description: 'Analyze requirements',
              tags: ['backend'],
              dependencies: [],
              priority: 1,
              timeoutMs: 60000,
            },
            dependencies: [],
            status: 'pending' as any,
          },
          {
            nodeId: 'n2',
            agentId: 'coder',
            taskDefinition: {
              id: 't2',
              type: 'code-generation' as any,
              description: 'Generate code',
              tags: ['backend'],
              dependencies: ['t1'],
              priority: 1,
              timeoutMs: 60000,
            },
            dependencies: ['n1'],
            status: 'pending' as any,
          },
          {
            nodeId: 'n3',
            agentId: 'tester',
            taskDefinition: {
              id: 't3',
              type: 'testing' as any,
              description: 'Run tests',
              tags: ['backend'],
              dependencies: ['t2'],
              priority: 1,
              timeoutMs: 60000,
            },
            dependencies: ['n2'],
            status: 'pending' as any,
          },
        ];

        const plan = await planRepo.create({
          projectId,
          intent,
          dag,
          estimatedCost: 0.003,
          estimatedDuration: 180000,
          status: 'pending_approval',
        });
        return plan;
      }),
    };

    // Mock DecisionCache, CostTracker, PromptCompiler
    const mockDecisionCache = {
      getCachedDecision: jest.fn().mockResolvedValue(null),
      cacheDecision: jest.fn(),
      buildKey: jest.fn().mockReturnValue('key'),
      computeContextHash: jest.fn().mockReturnValue('hash'),
    };

    const mockCostTracker = {
      checkBudget: jest.fn().mockResolvedValue({
        allowed: true,
        remaining: 10,
        currentSpend: 0,
        budgetLimit: 10,
      }),
      trackCost: jest.fn().mockResolvedValue(undefined),
    };

    const mockPromptCompiler = {
      compileSystemPrompt: jest.fn().mockReturnValue('system prompt'),
      registerModule: jest.fn(),
      getModuleCount: jest.fn().mockReturnValue(0),
    };

    // Mock QualityGatesService
    const mockQualityGates = {
      runLintGate: jest.fn().mockResolvedValue({ passed: true, issues: [] }),
      runSecurityGate: jest
        .fn()
        .mockResolvedValue({ passed: true, issues: [] }),
      runTestGate: jest.fn().mockResolvedValue({ passed: true, issues: [] }),
    };

    const resultEvaluator = new ResultEvaluator(
      mockQualityGates as any,
      vibeConfig,
    );

    const scheduler = new Scheduler(
      queueProvider,
      planRepo as any,
      mockVcs as any,
    );

    const workerPoolManager = new WorkerPoolManager(
      queueProvider,
      cache,
      agentRegistry,
      vibeConfig,
    );

    const traceContext = new TraceContext();

    orchestratorService = new OrchestratorService(
      mockPlanner as any,
      scheduler,
      resultEvaluator,
      traceContext,
      eventsGateway,
      mockDecisionCache as any,
      mockCostTracker as any,
      mockPromptCompiler as any,
      planRepo as any,
    );

    agentJobRunner = new AgentJobRunner(
      queueProvider,
      agentRegistry,
      contextCompiler,
      orchestratorService,
      executionRepo as any,
      workerPoolManager,
    );

    // Initialize — registers handlers for all agents
    await agentJobRunner.onModuleInit();
  });

  it('should execute the full pipeline from intent to completion', async () => {
    // Step 1: Create plan
    const plan = await orchestratorService.executeIntent(
      'Create a hello world app',
      'proj-1',
      { apiKey: 'test-key' },
    );
    const planId = plan._id?.toString() ?? (plan as any).id;

    expect(planId).toBeDefined();
    expect(plan.dag).toHaveLength(3);
    expect(plan.status).toBe('pending_approval');

    // Step 2: Approve plan → triggers dispatch → triggers agent execution
    await orchestratorService.approvePlan(planId);

    // Allow async processing to complete
    await new Promise((resolve) => setTimeout(resolve, 200));

    // Step 3: Verify all agents executed
    const finalPlan = planRepo._plans.get(planId);
    expect(finalPlan).toBeDefined();
    expect(finalPlan.status).toBe('completed');

    // All DAG nodes should be completed
    for (const node of finalPlan.dag) {
      expect(node.status).toBe('completed');
    }
  });

  it('should create AgentExecution records for each agent', async () => {
    const plan = await orchestratorService.executeIntent(
      'Build an API',
      'proj-1',
      { apiKey: 'test-key' },
    );
    const planId = (plan as any)._id ?? (plan as any).id;

    await orchestratorService.approvePlan(planId);
    await new Promise((resolve) => setTimeout(resolve, 200));

    // Should have 3 execution records (one per agent)
    expect(executionRepo.create).toHaveBeenCalledTimes(3);

    // Each should start as 'running'
    for (const call of executionRepo.create.mock.calls) {
      expect(call[0].status).toBe('running');
    }

    // Each should be updated to 'completed'
    const completedUpdates = executionRepo.update.mock.calls.filter(
      (call: any[]) => call[1].status === 'completed',
    );
    expect(completedUpdates).toHaveLength(3);
  });

  it('should emit WebSocket events for pipeline lifecycle', async () => {
    const plan = await orchestratorService.executeIntent(
      'Create project',
      'proj-1',
      { apiKey: 'test-key' },
    );
    const planId = (plan as any)._id ?? (plan as any).id;

    await orchestratorService.approvePlan(planId);
    await new Promise((resolve) => setTimeout(resolve, 200));

    const emittedEvents = eventsGateway.emitExecutionEvent.mock.calls.map(
      (call: any[]) => call[1].type,
    );

    expect(emittedEvents).toContain('plan_created');
    expect(emittedEvents).toContain('execution_started');
    expect(emittedEvents).toContain('node_completed');
    expect(emittedEvents).toContain('pipeline_completed');
  });

  it('should execute DAG nodes in dependency order', async () => {
    const executionOrder: string[] = [];

    // Override mock agents to track execution order
    const trackedAgents = ['analyst', 'coder', 'tester'];
    for (const id of trackedAgents) {
      const agent = agentRegistry.get(id);
      const originalExecute = agent.execute.bind(agent);
      (agent as any).execute = async (input: AgentInput) => {
        executionOrder.push(id);
        return originalExecute(input);
      };
    }

    const plan = await orchestratorService.executeIntent(
      'Build sequential app',
      'proj-1',
      { apiKey: 'test-key' },
    );
    const planId = (plan as any)._id ?? (plan as any).id;

    await orchestratorService.approvePlan(planId);
    await new Promise((resolve) => setTimeout(resolve, 200));

    // Analyst must run before coder, coder before tester
    expect(executionOrder).toEqual(['analyst', 'coder', 'tester']);
  });

  it('should handle agent failure and mark plan as failed', async () => {
    // Make coder agent fail
    const coderAgent = agentRegistry.get('coder');
    (coderAgent as any).execute = async () => {
      throw new Error('LLM rate limit exceeded');
    };

    const plan = await orchestratorService.executeIntent(
      'Build failing app',
      'proj-1',
      { apiKey: 'test-key' },
    );
    const planId = (plan as any)._id ?? (plan as any).id;

    await orchestratorService.approvePlan(planId);
    await new Promise((resolve) => setTimeout(resolve, 200));

    const finalPlan = planRepo._plans.get(planId);
    expect(finalPlan.status).toBe('failed');

    // Analyst should have completed, coder failed, tester skipped
    const analystNode = finalPlan.dag.find((n: any) => n.agentId === 'analyst');
    const coderNode = finalPlan.dag.find((n: any) => n.agentId === 'coder');
    const testerNode = finalPlan.dag.find((n: any) => n.agentId === 'tester');

    expect(analystNode.status).toBe('completed');
    expect(coderNode.status).toBe('failed');
    expect(testerNode.status).toBe('skipped');

    // Failure execution record should exist
    const failedUpdates = executionRepo.update.mock.calls.filter(
      (call: any[]) => call[1].status === 'failed',
    );
    expect(failedUpdates).toHaveLength(1);
    expect(failedUpdates[0][1].errorDetails.message).toBe(
      'LLM rate limit exceeded',
    );
  });
});
