name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - master
      - Develop
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  deploy-preview:
    if: github.ref == 'refs/heads/Develop'
    runs-on: ubuntu-latest
    name: Deploy Preview
    steps:
      - name: Trigger Vercel Deploy
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_xqAqp1bIVKaMcO4nrgBRjtl6DY02/AuCNIwUBmn"

  deploy-production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Deploy Production
    steps:
      - name: Trigger Vercel Deploy
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_xqAqp1bIVKaMcO4nrgBRjtl6DY02/qqTk6Osowz"
